<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>try-catch-finally</title>
  </head>
  <body>
    <script>
          // try ... catch ... finally


      try{
        alert('try');
        if(confirm('Make an error?')) BAD_CODE();
      }catch (e){
        alert('catch');
      }finally {
       alert('finally');
      }


      //-------------------------------------------------------

      let num = +prompt("Enter a positive integer number?", 35)
      let diff, result;

      function fib(n){
        if(n<0 || Math.trunc(n) !=n){
          throw new Error("Must not be negative, and also an integer.");
        }
        return n <=1 ? n : fib(n - 1) + fib(n - 2);
      }

      let start = Date.now();
      try {
        result = fib(num);
      }catch (e){
        result = 0;
      }finally{
        diff = Date.now() - start;
      }
      alert(result || "error occurred");
      alert(`execution took ${diff}ms`);


      //-------------------------------------------------------------

      function func(){
        try{
          return 1;
        }catch(e) {
          /*....*/ 
        } finally {
          alert(`finally`);
        }
      }
      
      alert(func()); // first work alert from finally, and then this one


      //-----------------------------------------------------------------------

      /*
      message
Error message.
url
URL of the script where error happened.
line, col
Line and column numbers where error happened.
error
Error object.

      */

      window.onerror = function(message, url, line, col, error) {
        alert(`${message}\n At ${line}:${col} of ${url}`);
      };

      function readData() {
        badFunc();            // Whoops, something went wrong!
      }
      readData();

    </script>
  </body>
</html>
